### ISSUE TITLE
Overlap

### ISSUE THREAD

**Issue by menardmam** [AshesOfOwls/jquery.shapeshift#12]
Here is my SUPER DUPER SIMPLE DEMO (to understand) and for some bizzare reason... there is an overlap from the hell.... can you tell me how to fix it ?

http://studioteknik.com/jquery.shapeshift-master/demo/mam.html

thanks in advance

**Comment by AshesOfOwls** [comment]
Ah yeah, that is because shapeshift requires that all elements be the same width.

Think of the way it sorts elements as if there were a bunch of columns next to each other. It will iterate over all the child elements and place each one into the current column with the lowest height. The way it calculates the width of each column is by taking the first child element and getting its width.

Currently I have a branch created which will bring in a feature that allows for elements with varying widths, however that will have the same caveat as the first which means each element has to have a common multiple. For instance, if you have a gutter of 10 pixels, and the first element is 100 pixels wide, an element that spans two columns will have to be 210 pixels wide. It will be a few days before I can get this finished and pulled into the master branch though.

Hope that helps.

**Comment by menardmam** [comment]
Make sens, tks

Marc-André Ménard
514-222-1070

Studioteknik.com
Notreaventure.com
Notre-petite-famille.com
