### ISSUE TITLE
Grid items with multiple column span

### ISSUE THREAD

**Issue by brooksryba** [AshesOfOwls/jquery.shapeshift#2]
Shapeshift does not seem to support items that span multiple columns. Is there any plan to support this in the furture?

**Comment by AshesOfOwls** [comment]
The short answer is yes, but it comes with some caveats.

The main problem is that the current algorithm uses strict left to right top to bottom rendering, so lets say you have an item that is in the last column, but it spans two wide. You then have to remove it from the last column and find the column with the smallest height that also has a spot open next to it. This leads to a lot of blank spaces in the current system, so it needs to be redesigned slightly to fix that.

It also because of that may limit the user to only items that have a consistent height / width (a more squareish grid) when using that item, but that's something I'll decide on when I get to it. It will probably be something that i do within the next few weeks, maybe I'll tackle it over winter holiday break.

**Comment by AshesOfOwls** [comment]
I have two issues regarding this change, I am going to consolidate them into one. I have created a new branch which hopefully will get to resolving this issue.

You can find the new discussion on this ticket.

https://github.com/McPants/jquery.shapeshift/issues/8

**Comment by abhishekpathak919** [comment]
why this forth grid is overlapping on top please give me a solution ASAP 

actually it should come in last row 
![grid](https://cloud.githubusercontent.com/assets/14105230/9652324/d55bf798-5237-11e5-8b12-e64388329349.png)

**Comment by utkarsharma2** [comment]
@McPants, I am facing similar issue as abhishekpathak919 did. Kindly help me with the it.
