### ISSUE TITLE
Use of trash

### ISSUE THREAD

**Issue by digitalxpIT** [AshesOfOwls/jquery.shapeshift#21]
I'll try to use this very nice plugin. But could you help me to the use of trash!

I enable it.... 

  $containers.shapeshift({
  enableTrash: true,

but never change in the page!

**Comment by AshesOfOwls** [comment]
Could you provide an example I can look at?

The trash really isn't anything physical, and what I mean by that is it doesn't change the visuals of anything. It simply allows for other items to be dragged into that container and be destroyed.

**Comment by digitalxpIT** [comment]
Hi, I'll try this solution: www.mimanchitu.it/new if you move a div on trash, that's delete!
Another question, Is'it possible to save the div position?!

**Comment by AshesOfOwls** [comment]
Yup thats exactly how it should work :+1: 

It is technically possible to save the position of the div. The way that Shapeshift works is aligning divs from top to bottom, left to right. So therefore you cannot save the literal X/Y position, but you can save the order that the items appear and as long as they stay the same height/width then they will always reappear in the same spot as last time.

There are several events to listen to in order to retrieve the position of the divs all of which are documented at the bottom of the readme. Here are the examples, you would replace $containers with the jQuery element of the container you want to listen to.

``` javascript
$containers.on("ss-event-dragged", function(e, selected) {
  var $selected = $(selected);
  console.log("This is the item being dragged:", $selected);
});

$containers.on("ss-event-dropped", function(e, selected) {
  var $selected = $(selected)
  console.log("The dropped item is:", $selected)

  // Get the index position of each object
  $objects = $(this).children();
  $objects.each(function(i) {
    console.log("Get the index position:", i)
    console.log("Get the current element:", $(this))
  });
});

$containers.on("ss-event-destroyed", function(e, selected) {
  var $selected = $(selected);
  console.log("This is the item being destroyed:", $selected);
});
```

**Comment by AshesOfOwls** [comment]
Closing this, if you need more help let me know.
