### ISSUE TITLE
Drop placeholder?

### ISSUE THREAD

**Issue by tudor2004** [AshesOfOwls/jquery.shapeshift#22]
First of all thank you for this very great plugin. It has exactly what i need but i want to ask you if it is possible to make a drop placeholder? Like on jQuery Ui Sortable http://jqueryui.com/sortable/#placeholder

**Comment by AshesOfOwls** [comment]
Definitely possible, the problem I am having is that there are so many feature requests and I can't get them in fast enough. I can promise you I will eventually get to it, but I honestly have no idea when it will be.

**Comment by tudor2004** [comment]
I understand. The thing is that i managed to find a solution by calculating the target offset during the drag function. The problem is that sometimes the placeholder was placed outside of the wrapper. I should mention that the placeholder was appended outside of the shapeshift container. Anyway, thank you for the quick answer and congrats for this awsome plugin!

**Comment by nicksp** [comment]
I'm also in need of such a feature. Could you please help me to recreate that option? I wanna see it in my currently developing project. What and where should i add into code? Looking forward to your help!

**Comment by AshesOfOwls** [comment]
I will definitely include this in the 2.0 release, but I don't expect to add it into the current version so that I can get 2.0 out faster.

If you would like to personally modify the code, here is how I would do it:

When you move an item to a new container, you could have to manually drop in a div with a class of something like "ss-placeholder". Next, on the arrange function it prevents arranging anything with the class ss-moving, because that is what the currently dragged items class is. So during the arrange function, instead of skipping over the ss-moving element, instead arrange the ss-placeholder element to where the ss-moving class would have been. At this time you will also have to set the height and width of the placeholder to match the ss-moving element. Then when the dragged item has been dropped or changes containers, remove the ss-placeholder element.

You might also have to prevent the ss-placeholder class from being an "active element" so that the program doesn't think it should arrange it with the other elements.

Hope that helps.

**Comment by AshesOfOwls** [comment]
I got this successfully into 2.0 and it is pushed into that branch if you want to check it out. The full drag and drop is still not ready in 2.0 though.

**Comment by nicksp** [comment]
Huge thanks. That's really what i need. But demo seems not working. Placeholder only appears at first position....

**Comment by AshesOfOwls** [comment]
Yeah I'm still getting the refactored version to 100% so for now its just forcing every dragged item to the 0th position. I should be able to get targeted drag/drop in by the end of day since I have nothing else to work on today.

**Comment by nicksp** [comment]
Ah, i see. But the placeholder feature is already completed, isn't it? So i could integrate it into my project based on the first plugin edition, right?

**Comment by AshesOfOwls** [comment]
Yup, if you can figure out where to copy/paste the code into. I am trying to get 2.0 out the door asap but I have learned its best not to set a target date because I haven't been able to stick to those dates. It's relatively similar so it shouldn't be too hard to get working into the old code if you want to spend the time doing so.

**Comment by AshesOfOwls** [comment]
Alright targeted drag and drop is now in 2.0, but I still need to allow for it to work across multiple containers and get some of the element whitelisting options back in.

**Comment by alanheppenstall** [comment]
Thanks, you're doing great work!

**Comment by AshesOfOwls** [comment]
This is officially in 2.0 which will be released sometime tonight. I am going to close this issue, you can follow the release progress in the 'Multiwidth' issue.
