### ISSUE TITLE
Documentation: how to set options

### ISSUE THREAD

**Issue by Pumpapa** [AshesOfOwls/jquery.shapeshift#28]
I'm impressed by the demo, but stuck for lack of documentations. 
Out of the box I get a "Shapeshift ERROR: There are child elements that have a larger colspan than the minimum columns set through options.
options.minColumns has been set to 7"

But how do I set options? The docs don't seem to tell me. What does the last line mean?

Cheers -- Pumpapa

**Comment by AshesOfOwls** [comment]
Yeah sorry this is my first public plugin so it's been a learn as you go situation in terms of documentation.

When normally initializing Shapeshift on a container, you would just call:

```
$('.container').shapeshift()
```

To set options on it, just include them as a hash within the initialization. For example,

```
$('.container').shapeshift({
    enableDrag: false,
    enableResize: false,
    align: "left",
    minColumns: 3,
    gutterY: 20
});
```

The reason you got that minimum columns error is because there are some tests that take place when Shapeshift is initialized that make sure the options that are set don't break the code. In this case, there was a child element that spanned 7 columns wide but the minimum columns was still at the default 1. The error detection will automatically change the minColumns option to 7 because you cannot have less columns than a child can span across.

I'll see if I can throw some more basic examples up on the wiki, as well as more documentation related to error messages.

**Comment by AshesOfOwls** [comment]
I am starting to create more examples that also show the code. You can access them through the examples link on the top right of the demo.

Heres the first example I have done, more to come soon.
http://mcpants.github.io/jquery.shapeshift/mosaic.html

**Comment by Pumpapa** [comment]
Hey Scott,

Thanks. I'm stuck in another project but I will get back to this asap.

Best,

Pum

Babelfish BV http://www.babelfish.nl/
Mobiele Innovatie, Grip op Software.
Pum Walters
06-12049590    035-6221011
pum@babelfish.nl

Dr H.R. (Pum) Walters RI         (LinkedIn)http://linkedin.com/in/pumwalters
Innovator, Mediator, Software Engineer
TOGAF9 certified, Registerinformaticus
LRGD geregistreerd Gerechtelijk Deskundige
Prince2 Foundation Certified

**Comment by AshesOfOwls** [comment]
Sounds good, feel free to reopen this if you still have issues.
