### ISSUE TITLE
Event Dropped

### ISSUE THREAD

**Issue by iraycd** [AshesOfOwls/jquery.shapeshift#3]
$containers.on("ss-event-dropped", function(e, $selected) {
  // Get the new position for the dropped item
  var position = $selected.index();
  // Get the index position of each object
  $objects = $(this).children();
  $objects.each(function(i) {
    position[i] = $(this).index();
  });
});

Uncaught TypeError: Object #<HTMLDivElement> has no method 'index'

**Comment by AshesOfOwls** [comment]
Will look into this today.

**Comment by AshesOfOwls** [comment]
Ok, it turns out that the $selected object getting passed back through the function was not a jQuery object by default.

So instead, it must now look like this:

$containers.on("ss-event-dropped", function(e, selected) {
// Get the new position for the dropped item
var position = $(selected).index();
// Get the index position of each object
$objects = $(this).children();
$objects.each(function(i) {
position[i] = $(this).index();
});
});

The readme has been updated accordingly.

**Comment by iraycd** [comment]
Thank you
