### ISSUE TITLE
Multiple width

### ISSUE THREAD

**Issue by wintercounter** [AshesOfOwls/jquery.shapeshift#8]
Hey, the plugin is awsome!

Anyway it would be nice if i can have multiple width too. I having some kind of widget system. Currently i'm using masonry to do a drag & drop like thing and it works great but it has 1-2 bugs... I know it's not easy to achieve this, but maybe a solution where you can use a multiplier of the base width (1x170px,2x170px, etc.) to have several sizes would work nice... also support for percentage for fluid/responsive layouts of course...

**Comment by AshesOfOwls** [comment]
Thank you. This is something that I have been wanting to do for a while now but as you said it's not too easy. I was thinking about looking over it during the next few days and see if I can sketch something out. My main problem is that I want to keep it as dynamic as possible, so that you can adjust padding between columns and not have that affect the static html element it is arranging.

Currently the plugin doesn't touch the size of the elements, it is up to the user to define the height and width before it is arranged. With the multiple widths I might have to require the plugin to size the elements manually, which may also mean more options have to be passed with each object. I could go on forever though with this though heh.

I'll let ya know when I get moving on it.

**Comment by AshesOfOwls** [comment]
Sorry I completely missed your other bug issue regarding fluid/responsive layouts. Could you elaborate on this? It does conform to responsive layouts, but I assume you mean a way to add some sort of padding to the container on both sides?

I also created a new branch called multiwidth which will try to solve the multi column issue.

**Comment by lukju** [comment]
what is the statatus of this work? i've checked your branch "multiwith" and seen that drag/drop does not work there...
have you some plans to do some more work in this area?

**Comment by AshesOfOwls** [comment]
Yup! I am just in the process of making the multiwidth faster, currently after about 200 items it lags a lot so I want to see if I can possibly get that number around 500 before I add in drag and drop. It should be pretty quick to put in too because the old code won't change much with the new refactored version. Sorry for the wait, it's been more complicated than I previously thought.

**Comment by lukju** [comment]
perfect. thank you for this update. 
i think ou've done a great job with ShapeShift - looks good and interesting. I will invest some more time as soon as multicolumn widgets will be possibile. I really hope that you will be successful :-)

**Comment by AshesOfOwls** [comment]
Another update, I made some decent progress today and simplified the logic decently well. I might be able to get version 2.0 up to a production ready state by the end of this weekend.

**Comment by andersonamuller** [comment]
Good news, I'm waiting for the new responsive, multi-width and draggable to implement something in my project. Keep the nice work :+1:

**Comment by MSch** [comment]
This is awesome! Looking forward to this very much. Thanks for your work!

**Comment by AshesOfOwls** [comment]
Another update, I am currently reintegrating drag and drop into 2.0. Once that is done I will have to do some cross browser testing / miscellaneous tweaking and then it should be good to go.

**Comment by lukju** [comment]
It seems that you mastered the beforementioned performance problems? Congratulations for that and good luck for the Rest of the work. Thank you for your effort

**Comment by AshesOfOwls** [comment]
Thanks! Yeah it seems like it's about as good as I can make it for no, hopefully once 2.0 is up I can find some people to collaborate with and try to make the sorting algorithm better. I tried it on a 5000 element grid though and it was going fine aside from a few hiccups in regards to animation which there isn't much I can do about aside from including an option to disable the jquery animate function when more than X elements are in a container.

I'll be working on it a bunch today, hopefully I make some good progress and get it out the door soon.

**Comment by websnacks** [comment]
Hi, can't wait for the multi-width fix! I am using Shapeshift for a project now, but I really need multi-width. Let me know when you fixed it, I will than show you my project which you can add to the section 'Sites Using Shapeshift' :)

**Comment by AshesOfOwls** [comment]
Will do, this thread will be the best place to keep up to date with the multi width stuff. I just pushed up to the 2.0 branch today with cross container drag and drop. Not too much left!

**Comment by AshesOfOwls** [comment]
I am updating the Readme, home stretch!

**Comment by MSch** [comment]
\o/

**Comment by AshesOfOwls** [comment]
Going to release 2.0 sometime tonight. It could probably go out now but I want to double check everything once I get home to make sure that I didn't miss anything blaring.

**Comment by AshesOfOwls** [comment]
Released

**Comment by anuccio1** [comment]
Hey, I want to have the following functionality:

Have one tile in my board always be in the bottom right. Can't be dragged, and nothing can be moved to the right or under it. Is there a way already to make one tile remain in a static position? Let me know. Thanks!
